export const ERROR_MAP = {
  AE001: "User is exsit",
  AE002: "User is not exist",
  AE003: "User name or password is wrong",
  AE004: "Store is not exist",
  AE005: "Reel is not exist",
  AE006: "Coupon is not valid to claim",
  AE007: "Coupon was claimed",
  AE008: "User rated this shop",
  AE009: "Account is block",
  AE010: "Email is registered",
  AE011: "Coupon is not exist",
  AE012: "Customer is not exist",
  AE013: "Customer have not claimed this coupon",
  AE014: "User used this coupon",
  AE015: "Coupon over used",
  AE016: "Coupon is not your store",
  AE017: "Coupon is expired",
  AE018: "Old password is wrong",
  AE019: "The account can not change password",
  AE020: "Code not found",
  AE021: "Code is expired",
  AE022: "Code is not verified",
  AE023: "Coupon code is exist",
  AE024: "Start date must be less than expired date",
  AE025: "must be more than now",
  AE026: "File is not found",
  AE027: "Reel is not exist",
  AE028: "This account has created a store before",
  AE029: "you don't have a store",
  AE030: "product name is exsit",
  AE031: "product does not exist",
  AE032: "Location already exists",
  AE033: "Staff is not exist",
  AE034: "coupon is not exist",
  AE035: "Mux webhooks verify header false",
  AE036: "coupons sold out",
  AE037: "you don't have this coupon yet",
  AE038: "not have access",
  AE039: "banner does not exist",
  AE040: "category does not exist",
  AE041: "claim is not exist",
  AE042: "Your total bill is not enough to use coupon",
  AE043: "Invalid store coupon"
};
